import { test, expect } from '@playwright/test';
test('complete list workflow, keyboard, persistence and mobile', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Characters', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Army points' })).toContainText('2,000');
  const addUnit = async (bucket: string, query: string, choice?: string) => {
    await page.getByRole('button', { name: `Add unit to ${bucket}` }).click();
    await page.getByLabel('Search units').fill(query);
    await page.locator('.picker-list button').first().click();
    if (choice) await page.getByRole('button', { name: choice }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
  };
  await addUnit('Characters', 'cAlGaR');
  await expect(page.locator('.bucket').first().locator('.bucket-subtotal')).toContainText('155');
  await expect(page.locator('.remaining strong')).toHaveText('1,845');
  await addUnit('Characters', 'Captain with Jump Pack');
  await addUnit('Shooting', 'Hellblaster', '10 models 220 pts');
  await addUnit('Shooting', 'Hellblaster', '5 models 110 pts');
  await addUnit('Melee', 'Centurion Assault', '3 models 150 pts');
  await addUnit('Support', 'Wardens');
  await page.getByLabel('Move Captain with Jump Pack').selectOption('melee');
  await expect(page.getByRole('region', { name: 'Melee', exact: true })).toContainText('Captain with Jump Pack');
  await page.getByRole('button', { name: 'Remove Wardens Of Ultramar' }).click();
  const summary = await page.locator('.points-summary').innerText();
  await page.reload();
  await expect(page.locator('.points-summary')).toHaveText(summary);
  await expect(page.locator('.unit-row')).toHaveCount(5);
  await page.getByRole('button', { name: 'Add unit to Support' }).click();
  await expect(page.getByLabel('Search units')).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Add unit to Support' })).toBeFocused();
  for (let i = 0; i < 2; i++) await addUnit('Support', 'Thunderhawk');
  await expect(page.locator('.remaining strong')).toHaveText('-390');
  await page.screenshot({ path: '/tmp/teleportarium-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 390);
  await page.getByRole('button', { name: 'Add unit to Melee' }).click();
  await page.getByLabel('Search units').fill('not a real unit');
  await expect(page.getByText('No matching units. Try another name.')).toBeVisible();
  await page.getByLabel('Search units').fill('Hellblaster');
  await page.locator('.picker-list button').click();
  await page.screenshot({ path: '/tmp/teleportarium-picker-mobile.png', fullPage: true });
  await page.getByRole('button', { name: '5 models 110 pts' }).click();
  await page.screenshot({ path: '/tmp/teleportarium-mobile.png', fullPage: true });
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'Clear list' }).click();
  await expect(page.locator('.unit-row')).toHaveCount(8);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Clear list' }).click();
  await expect(page.locator('.unit-row')).toHaveCount(0);
  await page.reload();
  await expect(page.locator('.unit-row')).toHaveCount(0);
  expect(errors).toEqual([]);
});
test('corrupt storage does not crash', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('warhammer-list-builder:v1', '{broken'));
  await page.goto('/');
  await expect(page.locator('.unit-row')).toHaveCount(0);
});
test('stale references stay removable and excluded from totals', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('warhammer-list-builder:v1', JSON.stringify({ munitorumId: 'old', entries: [{ instanceId: 'old', unitId: 'old-unit', optionId: 'old-option', bucket: 'support' }] })));
  await page.goto('/');
  await expect(page.getByText('Unavailable in this snapshot · excluded from totals')).toBeVisible();
  await expect(page.locator('.stat strong').first()).toHaveText('0');
  await page.getByRole('button', { name: 'Remove old-unit' }).click();
  await expect(page.locator('.unit-row')).toHaveCount(0);
});
test('unavailable storage shows a warning while edits still work', async ({ page }) => {
  await page.addInitScript(() => {
    Storage.prototype.getItem = () => { throw new Error('Blocked'); };
    Storage.prototype.setItem = () => { throw new Error('Blocked'); };
  });
  await page.goto('/');
  await expect(page.getByRole('alert')).toContainText('Browser storage is unavailable');
  await page.getByRole('button', { name: 'Add unit to Characters' }).click();
  await page.getByLabel('Search units').fill('Calgar');
  await page.locator('.picker-list button').click();
  await expect(page.locator('.unit-row')).toHaveCount(1);
});
