import { test } from 'node:test';
import assert from 'node:assert/strict';
import { findMunitorum, munitorum } from '../src/data/munitorum/index.ts';
import { calculateEntryPoints, resolveEntry } from '../src/utils/points.ts';
import { decodeArmy } from '../src/utils/storage.ts';
const interim = findMunitorum('space-marines-interim-2026-09')!;
// Exact whitelist and prices from the user's supplied list and corrections.
const expected: [string, [number, number][]][] = [
  [
    "intercessor-squad",
    [
      [
        5,
        85
      ]
    ]
  ],
  [
    "inceptor-squad",
    [
      [
        3,
        130
      ],
      [
        6,
        260
      ]
    ]
  ],
  [
    "assault-intercessors-with-jump-packs",
    [
      [
        5,
        95
      ]
    ]
  ],
  [
    "vanguard-veteran-squad-with-jump-packs",
    [
      [
        5,
        110
      ],
      [
        10,
        220
      ]
    ]
  ],
  [
    "company-heroes",
    [
      [
        4,
        125
      ]
    ]
  ],
  [
    "bladeguard-veteran-squad",
    [
      [
        3,
        90
      ],
      [
        6,
        180
      ]
    ]
  ],
  [
    "sternguard-veteran-squad",
    [
      [
        5,
        105
      ],
      [
        10,
        210
      ]
    ]
  ],
  [
    "terminator-squad",
    [
      [
        5,
        190
      ],
      [
        10,
        380
      ]
    ]
  ],
  [
    "terminator-assault-squad",
    [
      [
        5,
        170
      ],
      [
        10,
        340
      ]
    ]
  ],
  [
    "infernus-squad",
    [
      [
        5,
        95
      ],
      [
        10,
        190
      ]
    ]
  ],
  [
    "hellblaster-squad",
    [
      [
        5,
        115
      ],
      [
        10,
        230
      ]
    ]
  ],
  [
    "desolation-squad",
    [
      [
        5,
        140
      ]
    ]
  ],
  [
    "aggressor-squad",
    [
      [
        3,
        90
      ],
      [
        6,
        180
      ]
    ]
  ],
  [
    "eradicator-squad",
    [
      [
        3,
        100
      ],
      [
        6,
        200
      ]
    ]
  ],
  [
    "eradicator-squad-with-heavy-bolters",
    [
      [
        3,
        100
      ],
      [
        6,
        215
      ]
    ]
  ],
  [
    "scout-squad",
    [
      [
        5,
        65
      ]
    ]
  ],
  [
    "infiltrator-squad",
    [
      [
        5,
        85
      ]
    ]
  ],
  [
    "incursor-squad",
    [
      [
        5,
        90
      ]
    ]
  ],
  [
    "eliminator-squad",
    [
      [
        3,
        85
      ]
    ]
  ],
  [
    "reiver-squad",
    [
      [
        5,
        85
      ]
    ]
  ],
  [
    "redemptor-dreadnought",
    [
      [
        1,
        170
      ]
    ]
  ],
  [
    "ballistus-dreadnought",
    [
      [
        1,
        150
      ]
    ]
  ],
  [
    "brutalis-dreadnought",
    [
      [
        1,
        160
      ]
    ]
  ],
  [
    "storm-speeder-hailstrike",
    [
      [
        1,
        110
      ]
    ]
  ],
  [
    "storm-speeder-hammerstrike",
    [
      [
        1,
        140
      ]
    ]
  ],
  [
    "storm-speeder-thunderstrike",
    [
      [
        1,
        140
      ]
    ]
  ],
  [
    "land-speeder",
    [
      [
        1,
        105
      ]
    ]
  ],
  [
    "repulsor",
    [
      [
        1,
        190
      ]
    ]
  ],
  [
    "repulsor-executioner",
    [
      [
        1,
        260
      ]
    ]
  ],
  [
    "land-raider",
    [
      [
        1,
        245
      ]
    ]
  ],
  [
    "gladiator-lancer",
    [
      [
        1,
        160
      ]
    ]
  ],
  [
    "gladiator-reaper",
    [
      [
        1,
        165
      ]
    ]
  ],
  [
    "rhino",
    [
      [
        1,
        70
      ]
    ]
  ],
  [
    "impulsor",
    [
      [
        1,
        70
      ]
    ]
  ],
  [
    "captain-in-terminator-armour",
    [
      [
        1,
        90
      ]
    ]
  ],
  [
    "captain-in-gravis-armour",
    [
      [
        1,
        90
      ]
    ]
  ],
  [
    "librarian-in-phobos-armour",
    [
      [
        1,
        75
      ]
    ]
  ],
  [
    "lieutenant-with-combi-weapon",
    [
      [
        1,
        85
      ]
    ]
  ],
  [
    "captain-with-jump-pack",
    [
      [
        1,
        90
      ]
    ]
  ],
  [
    "chaplain-with-jump-pack",
    [
      [
        1,
        75
      ]
    ]
  ],
  [
    "chaplain-in-terminator-armour",
    [
      [
        1,
        75
      ]
    ]
  ],
  [
    "ancient-in-terminator-armour",
    [
      [
        1,
        75
      ]
    ]
  ],
  [
    "bladeguard-ancient",
    [
      [
        1,
        70
      ]
    ]
  ],
  [
    "apothecary",
    [
      [
        1,
        45
      ]
    ]
  ],
  [
    "apothecary-biologis",
    [
      [
        1,
        60
      ]
    ]
  ],
  [
    "roboute-guilliman",
    [
      [
        1,
        415
      ]
    ]
  ],
  [
    "marneus-calgar-in-armour-of-antilochus",
    [
      [
        1,
        180
      ]
    ]
  ],
  [
    "chief-librarian-tigurius",
    [
      [
        1,
        115
      ]
    ]
  ],
  [
    "cato-sicarius",
    [
      [
        1,
        115
      ]
    ]
  ],
  [
    "wardens-of-ultramar",
    [
      [
        6,
        115
      ]
    ]
  ],
  [
    "victrix-honour-guard",
    [
      [
        3,
        120
      ],
      [
        6,
        250
      ]
    ]
  ],
  [
    "commander-dante",
    [
      [
        1,
        140
      ]
    ]
  ],
  [
    "astorath",
    [
      [
        1,
        105
      ]
    ]
  ],
  [
    "sanguinary-guard",
    [
      [
        3,
        135
      ],
      [3, 150],
      [6, 275],
      [6, 290]
    ]
  ],
  [
    "death-company-marines-with-jump-packs",
    [
      [
        5,
        140
      ],
      [
        10,
        280
      ]
    ]
  ],
  [
    "kaius-konorius",
    [
      [
        1,
        100
      ]
    ]
  ]
];
test('interim includes exactly the supplied units, sizes and prices', () => {
  assert.equal(interim.units.length, 56);
  assert.equal(new Set(interim.units.map(unit => unit.id)).size, 56);
  assert.deepEqual(interim.units.map(unit => unit.id).sort(), expected.map(([id]) => id).sort());
  for (const [id, options] of expected) {
    const unit = interim.units.find(unit => unit.id === id)!;
    assert.deepEqual(unit.options.map(option => [Number.parseInt(option.label), option.points]), options);
    const official = munitorum.units.find(unit => unit.id === id);
    if (official) assert.equal(unit.name, official.name);
  }
  assert.equal(interim.units.reduce((count, unit) => count + unit.options.length, 0), 72);
  assert.match(interim.label, /unreleased/);
});
test('Sanguinary Guard tiers remain explicit and old 135-point entries still resolve', () => {
  const entry = { instanceId: 'sg', unitId: 'sanguinary-guard', optionId: '3-models', bucket: 'melee' as const };
  assert.equal(calculateEntryPoints(entry, interim), 135);
  for (const [optionId, points] of [['3-models-1st-to-2nd', 135], ['3-models-3rd', 150], ['6-models-1st-to-2nd', 275], ['6-models-3rd', 290]] as const) {
    assert.equal(calculateEntryPoints({ ...entry, optionId }, interim), points);
  }
  assert.equal(resolveEntry({ ...entry, optionId: '6-models' }, interim).option, undefined);
});
test('only supplied wargear is available and is charged per item', () => {
  const expected = [
    ['terminator-squad', 'Cyclone missile launcher', 10],
    ['terminator-assault-squad', 'Storm shield', 5],
    ['redemptor-dreadnought', 'Macro plasma incinerator', 10],
    ['repulsor-executioner', 'Heavy laser destroyer', 10],
    ['impulsor', 'Impulsor comms array', 10],
    ['victrix-honour-guard', 'Banner of Macragge', 15],
  ];
  const actual = interim.units.flatMap(unit => (unit.upgrades ?? []).map(wargear => [unit.id, wargear.label, wargear.points]));
  assert.deepEqual(actual.sort(), expected.sort());
  const unit = interim.units.find(unit => unit.id === 'victrix-honour-guard')!;
  assert.equal(calculateEntryPoints({ instanceId: 'v', unitId: unit.id, optionId: '3-models', bucket: 'melee', upgrades: [{ upgradeId: unit.upgrades![0].id, quantity: 2 }] }, interim), 150);
});
test('official tier IDs resolve to flat interim prices without guessing target tiers', () => {
  const entry = { instanceId: 'a', unitId: 'aggressor-squad', optionId: '3-models-3rd', bucket: 'shooting' as const };
  assert.equal(calculateEntryPoints(entry, interim), 90);
  assert.equal(resolveEntry({ unitId: 'eradicator-squad-with-melta-rifles', optionId: '3-models', bucket: 'shooting' as const, instanceId: 'a' }, munitorum).option, undefined);
  const loaded = decodeArmy(JSON.stringify({ munitorumId: interim.id, entries: [entry] }), munitorum.id);
  assert.equal(loaded.munitorumId, interim.id);
  assert.equal(calculateEntryPoints(loaded.entries[0], interim), 90);
});
